from __future__ import annotations

from datetime import datetime
from typing import Any
from unittest.mock import AsyncMock, patch

import pytest

from backend.agents.synthesis_agent import SynthesisAgent
from backend.exceptions.synthesis_exceptions import (
    SynthesisProviderError,
    SynthesisTimeoutError,
    SynthesisValidationError,
)
from backend.schemas.market_data import MarketData
from backend.schemas.news import NewsArticle
from backend.schemas.report import ResearchReport
from backend.schemas.research_report import SynthesizedReport
from backend.schemas.sentiment import SentimentAnalysis, SentimentScore


def _base_market_data() -> dict[str, MarketData]:
    from backend.schemas.market_data import FundamentalsData
    return {
        "AAPL": MarketData(
            ticker="AAPL",
            company_name="Apple Inc.",
            current_price=180.5,
            change_percent=1.2,
            fundamentals=FundamentalsData(
                market_cap=2_800_000_000_000,
                pe_ratio=28.5,
                dividend_yield=0.005,
            ),
        )
    }


def _base_news() -> list[NewsArticle]:
    return [
        NewsArticle(
            title="Apple beats Q4 earnings",
            description="Apple reported strong Q4 results.",
            url="https://example.com/apple-earnings",
            source="Reuters",
            published_at=datetime(2024, 1, 15),
        )
    ]


def _base_sentiment() -> SentimentAnalysis:
    return SentimentAnalysis(
        overall_sentiment=SentimentScore(label="positive", score=0.6, confidence=0.7),
        confidence=0.7,
        reasoning="earnings beat expectations",
        headline_sentiments=[],
        processing_metadata=SentimentAnalysis.model_fields["processing_metadata"].annotation(article_count=1),
    )


def _mock_llm_response() -> dict[str, Any]:
    return {
        "company": "Apple Inc.",
        "ticker": "AAPL",
        "generated_at": "2024-01-15T00:00:00",
        "executive_summary": "Apple demonstrated strong fundamentals with robust revenue growth.",
        "market_snapshot": "Trading at $180.50, up 1.2%.",
        "news_summary": "Recent news highlights strong Q4 earnings.",
        "sentiment_summary": "Overall positive sentiment around the stock.",
        "key_observations": ["Strong cash position", "Growing services revenue"],
        "risks": ["China exposure", "Regulatory pressure"],
        "confidence": 0.85,
        "disclaimer": (
            "This report is generated by an AI system for informational purposes only. "
            "It does not constitute investment advice. Please consult a qualified financial "
            "advisor before making investment decisions."
        ),
    }


def _mock_llm_response_limited() -> dict[str, Any]:
    return {
        "company": "Apple Inc.",
        "ticker": "AAPL",
        "generated_at": "2024-01-15T00:00:00",
        "executive_summary": "Summary.",
        "market_snapshot": None,
        "news_summary": None,
        "sentiment_summary": None,
        "key_observations": [],
        "risks": [],
        "confidence": 0.5,
        "disclaimer": "This report is for informational purposes only.",
    }


@pytest.mark.asyncio
async def test_successful_report_generation():
    with patch("backend.agents.synthesis_agent.get_llm_service") as mock_get:
        mock_llm = AsyncMock()
        mock_llm.default_model = "gpt-4o"
        mock_llm.structured_completion = AsyncMock(return_value=_mock_llm_response())
        mock_get.return_value = mock_llm

        agent = SynthesisAgent()
        report = await agent.generate_report(
            query="Analyze Apple Inc.",
            tickers=["AAPL"],
            market_data=_base_market_data(),
            news_articles=_base_news(),
            sentiment_analysis=_base_sentiment(),
        )

        assert isinstance(report, ResearchReport)
        assert report.query == "Analyze Apple Inc."
        assert report.tickers == ["AAPL"]
        assert len(report.sections) == 6
        assert report.sections[0].title == "Executive Summary"
        assert report.sections[1].title == "Market Snapshot"
        assert report.confidence_score == 0.85
        assert "investment advice" in report.disclaimer


@pytest.mark.asyncio
async def test_empty_news_input():
    with patch("backend.agents.synthesis_agent.get_llm_service") as mock_get:
        mock_llm = AsyncMock()
        mock_llm.default_model = "gpt-4o"
        mock_llm.structured_completion = AsyncMock(return_value=_mock_llm_response_limited())
        mock_get.return_value = mock_llm

        agent = SynthesisAgent()
        report = await agent.generate_report(
            query="Analyze Apple Inc.",
            tickers=["AAPL"],
            market_data=_base_market_data(),
            news_articles=[],
            sentiment_analysis=None,
        )

        assert isinstance(report, ResearchReport)
        assert report.news_sources == []
        news_section = next(s for s in report.sections if s.id == "news_summary")
        assert "No news articles available" in news_section.content
        assert len(report.sentiment_sources) == 0
        sentiment_section = next(s for s in report.sections if s.id == "sentiment_summary")
        assert "No sentiment data" in sentiment_section.content


@pytest.mark.asyncio
async def test_missing_market_data():
    with patch("backend.agents.synthesis_agent.get_llm_service") as mock_get:
        mock_llm = AsyncMock()
        mock_llm.default_model = "gpt-4o"
        mock_llm.structured_completion = AsyncMock(return_value=_mock_llm_response_limited())
        mock_get.return_value = mock_llm

        agent = SynthesisAgent()
        report = await agent.generate_report(
            query="Analyze Apple Inc.",
            tickers=["AAPL"],
            market_data={},
            news_articles=_base_news(),
            sentiment_analysis=None,
        )

        assert isinstance(report, ResearchReport)
        market_section = next(s for s in report.sections if s.id == "market_snapshot")
        assert "No market data available" in market_section.content


@pytest.mark.asyncio
async def test_malformed_llm_output():
    with patch("backend.agents.synthesis_agent.get_llm_service") as mock_get:
        mock_llm = AsyncMock()
        mock_llm.default_model = "gpt-4o"
        mock_llm.structured_completion = AsyncMock(return_value={"invalid": "response"})
        mock_get.return_value = mock_llm

        agent = SynthesisAgent()
        with pytest.raises(SynthesisValidationError):
            await agent.generate_report(
                query="Analyze Apple Inc.",
                tickers=["AAPL"],
                market_data=_base_market_data(),
                news_articles=_base_news(),
            )


@pytest.mark.asyncio
async def test_retry_behavior():
    with patch("backend.agents.synthesis_agent.get_llm_service") as mock_get:
        mock_llm = AsyncMock()
        mock_llm.default_model = "gpt-4o"
        mock_llm.structured_completion = AsyncMock(
            side_effect=[
                SynthesisProviderError("provider error"),
                SynthesisTimeoutError("timeout"),
                _mock_llm_response_limited(),
            ]
        )
        mock_get.return_value = mock_llm

        agent = SynthesisAgent()
        report = await agent.generate_report(
            query="Analyze Apple Inc.",
            tickers=["AAPL"],
            market_data=_base_market_data(),
            news_articles=_base_news(),
        )

        assert isinstance(report, ResearchReport)
        assert mock_llm.structured_completion.call_count == 3


@pytest.mark.asyncio
async def test_schema_validation():
    with pytest.raises(Exception):
        SynthesizedReport(
            company="Apple Inc.",
            generated_at=datetime.utcnow(),
            executive_summary="Summary.",
            key_observations=[],
            risks=[],
            disclaimer="Disclaimer.",
        )
