# EquiPilot AI - Report Schemas
# Pydantic models for research report structures

from datetime import datetime
from typing import Any

from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Source citation for report claims."""

    id: str
    type: str = Field(..., description="market_data, news, sentiment, llm")
    title: str
    url: str | None = None
    source: str
    date: datetime | None = None
    snippet: str | None = None
    relevance: float = Field(default=1.0, ge=0.0, le=1.0)

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat() if v else None}


class ReportSection(BaseModel):
    """Individual section of a research report."""

    id: str
    title: str
    level: int = Field(default=1, ge=1, le=3, description="Heading level (1-3)")
    content: str = Field(..., description="Section content in markdown")
    citations: list[Citation] = Field(default_factory=list)
    subsections: list["ReportSection"] = Field(default_factory=list)
    order: int = 0

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat() if v else None}


class ResearchReport(BaseModel):
    """Complete research report."""

    # Metadata
    request_id: str
    query: str
    tickers: list[str]
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    model_used: str = "gpt-4o"

    # Report structure
    executive_summary: str = Field(..., description="High-level summary")
    sections: list[ReportSection] = Field(default_factory=list)

    # Data references
    market_data_sources: list[Citation] = Field(default_factory=list)
    news_sources: list[Citation] = Field(default_factory=list)
    sentiment_sources: list[Citation] = Field(default_factory=list)

    # Quality metrics
    total_citations: int = 0
    unique_sources: int = 0
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)

    # Disclaimer
    disclaimer: str = (
        "This report is generated by an AI system for informational purposes only. "
        "It does not constitute investment advice. Please consult a qualified financial "
        "advisor before making investment decisions."
    )

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class ReportGenerationRequest(BaseModel):
    """Request for report generation."""

    query: str
    tickers: list[str]
    market_data: dict[str, Any]
    news_articles: list[dict[str, Any]]
    sentiment_analysis: dict[str, Any] | None = None
    max_length: int = 5000
    include_disclaimer: bool = True
    model: str = "gpt-4o"


class ReportFormat(BaseModel):
    """Report output format."""

    MARKDOWN: str = "markdown"
    HTML: str = "html"
    JSON: str = "json"
    PDF: str = "pdf"

    def __init__(self, **data):
        super().__init__(**data)

    model_config = {"extra": "forbid"}


class ReportExportRequest(BaseModel):
    """Request to export report in specific format."""

    report_id: str
    format: str = "markdown"
    include_metadata: bool = True
