# EquiPilot AI - Report Schemas
# Pydantic models for research report structures

from datetime import datetime
from typing import List, Optional, Dict, Any
from pydantic import BaseModel, Field


class Citation(BaseModel):
    """Source citation for report claims."""

    id: str
    type: str = Field(..., description="market_data, news, sentiment, llm")
    title: str
    url: Optional[str] = None
    source: str
    date: Optional[datetime] = None
    snippet: Optional[str] = None
    relevance: float = Field(default=1.0, ge=0.0, le=1.0)

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat() if v else None}


class ReportSection(BaseModel):
    """Individual section of a research report."""

    id: str
    title: str
    level: int = Field(default=1, ge=1, le=3, description="Heading level (1-3)")
    content: str = Field(..., description="Section content in markdown")
    citations: List[Citation] = Field(default_factory=list)
    subsections: List["ReportSection"] = Field(default_factory=list)
    order: int = 0

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat() if v else None}


class ResearchReport(BaseModel):
    """Complete research report."""

    # Metadata
    request_id: str
    query: str
    tickers: List[str]
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    model_used: str = "gpt-4o"

    # Report structure
    executive_summary: str = Field(..., description="High-level summary")
    sections: List[ReportSection] = Field(default_factory=list)

    # Data references
    market_data_sources: List[Citation] = Field(default_factory=list)
    news_sources: List[Citation] = Field(default_factory=list)
    sentiment_sources: List[Citation] = Field(default_factory=list)

    # Quality metrics
    total_citations: int = 0
    unique_sources: int = 0
    confidence_score: float = Field(default=0.0, ge=0.0, le=1.0)

    # Disclaimer
    disclaimer: str = (
        "This report is generated by an AI system for informational purposes only. "
        "It does not constitute investment advice. Please consult a qualified financial "
        "advisor before making investment decisions."
    )

    class Config:
        json_encoders = {datetime: lambda v: v.isoformat()}


class ReportGenerationRequest(BaseModel):
    """Request for report generation."""

    query: str
    tickers: List[str]
    market_data: Dict[str, Any]
    news_articles: List[Dict[str, Any]]
    sentiment_analysis: Optional[Dict[str, Any]] = None
    max_length: int = 5000
    include_disclaimer: bool = True
    model: str = "gpt-4o"


class ReportFormat(str):
    """Report output format."""

    MARKDOWN = "markdown"
    HTML = "html"
    JSON = "json"
    PDF = "pdf"


class ReportExportRequest(BaseModel):
    """Request to export report in specific format."""

    report_id: str
    format: ReportFormat = ReportFormat.MARKDOWN
    include_metadata: bool = True